# Generated by Django 5.1.2 on 2025-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.jpg', upload_to='covers'),
        ),
    ]
